import type { MetadataRoute } from "next";

import { APP_DESCRIPTION, APP_NAME, APP_TAGLINE } from "@/lib/brand";

/**
 * Web app manifest.
 *
 * Two reasons this is not cosmetic:
 * - iOS Safari only delivers web push to a site installed to the home screen, and
 *   installing requires a manifest. Without it, push silently never works on
 *   iPhone.
 * - The app already registers a service worker, so it is most of the way to
 *   installable; the manifest is what lets a browser actually offer that.
 *
 * `standalone` so an installed copy opens without browser chrome, which matters
 * for a video call where vertical space is scarce.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${APP_NAME} — ${APP_TAGLINE}`,
    short_name: APP_NAME,
    description: APP_DESCRIPTION,
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#09090b",
    theme_color: "#6366f1",
    orientation: "any",
    categories: ["business", "productivity"],
    icons: [
      {
        // Generated by `icon.tsx`, so there is one source of truth for the mark.
        src: "/icon",
        sizes: "32x32",
        type: "image/png",
      },
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
