/**
 * Generates a VAPID keypair and appends it to `.env`.
 *
 * Writes directly to the file rather than printing, so the private key never
 * lands in a terminal log or a chat transcript. Refuses to overwrite an existing
 * keypair: rotating it invalidates every push subscription already stored, which
 * silently stops notifications for everyone who has subscribed.
 */
const fs = require("node:fs");
const path = require("node:path");

const webpush = require("web-push");

const ENV_PATH = path.resolve(process.cwd(), ".env");

const existing = fs.existsSync(ENV_PATH)
  ? fs.readFileSync(ENV_PATH, "utf8")
  : "";

if (existing.includes("VAPID_PRIVATE_KEY=")) {
  console.log(
    "VAPID keys already present in .env — leaving them alone. Delete both VAPID_ lines first if you really want to rotate.",
  );
  process.exit(0);
}

const keys = webpush.generateVAPIDKeys();

const block = [
  "",
  "# Web push (VAPID). Generated by scripts/generate-vapid.js.",
  "# The public key is sent to the browser; the private key must stay secret.",
  "# Rotating these invalidates every stored PushSubscription.",
  `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${keys.publicKey}`,
  `VAPID_PRIVATE_KEY=${keys.privateKey}`,
  "# Contact address required by the push protocol. Any mailto: you control.",
  "VAPID_SUBJECT=mailto:admin@meshasec.com",
  "",
].join("\n");

const needsNewline = existing.length > 0 && !existing.endsWith("\n");

fs.appendFileSync(ENV_PATH, `${needsNewline ? "\n" : ""}${block}`);

console.log("Wrote NEXT_PUBLIC_VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY and");
console.log("VAPID_SUBJECT to .env. The private key was not printed.");
